version: '3'

services:
  server:
    build: ./server
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - .:/app
    networks:
      - label-gallary-nw
    env_file:
      - ./server/.env

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - label-gallary-nw

  client:
    build: ./client
    command: ["npm", "start"]
    volumes:
      - ./client:/LabelGallary/client
      - node-modules:/LabelGallary/client/node_modules
    ports:
      - "3000:3000"
    networks:
      - label-gallary-nw
    env_file:
      - ./client/.env

volumes:
  node-modules:

networks:
  label-gallary-nw:
    driver: bridge