# Generated by Django 3.2.21 on 2023-11-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20231120_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='files',
            field=models.ManyToManyField(related_name='label_files', to='images.File'),
        ),
        migrations.AlterField(
            model_name='file',
            name='labels',
            field=models.ManyToManyField(related_name='label_files', to='images.Label'),
        ),
    ]
